name: SSPanel Mining

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # 每天凌晨2点运行
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  test-chromedriver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Get Chrome version
      id: chrome-version
      run: |
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F'.' '{print $1}')
        echo "chrome_version=$CHROME_VERSION" >> $GITHUB_OUTPUT
        echo "Chrome version: $CHROME_VERSION"
    
    - name: Download ChromeDriver
      run: |
        # 清理旧文件
        sudo rm -rf /usr/local/bin/chromedriver
        sudo rm -rf /tmp/chromedriver*
        
        # 尝试多个下载源
        CHROME_VERSION="${{ steps.chrome-version.outputs.chrome_version }}"
        echo "Attempting to download ChromeDriver for Chrome version: $CHROME_VERSION"
        
        # 源1: Google Storage
        if [ "$CHROME_VERSION" -ge 115 ]; then
          # Chrome 115+ 使用新的下载方式
          CHROMEDRIVER_VERSION="120.0.6099.109"
        else
          # 旧版本Chrome
          CHROMEDRIVER_VERSION="$CHROME_VERSION.0.6045.105"
        fi
        
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # 尝试下载
        DOWNLOAD_SUCCESS=false
        
        # 尝试源1: Google Storage
        if ! $DOWNLOAD_SUCCESS; then
          echo "Trying Google Storage..."
          wget -q --timeout=30 --tries=3 -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" && DOWNLOAD_SUCCESS=true || echo "Google Storage failed"
        fi
        
        # 尝试源2: GitHub Releases
        if ! $DOWNLOAD_SUCCESS; then
          echo "Trying GitHub Releases..."
          wget -q --timeout=30 --tries=3 -O /tmp/chromedriver.zip "https://github.com/GoogleChromeLabs/chrome-for-testing/releases/download/$CHROMEDRIVER_VERSION/chromedriver-linux64.zip" && DOWNLOAD_SUCCESS=true || echo "GitHub Releases failed"
        fi
        
        # 尝试源3: Google CDN
        if ! $DOWNLOAD_SUCCESS; then
          echo "Trying Google CDN..."
          wget -q --timeout=30 --tries=3 -O /tmp/chromedriver.zip "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" && DOWNLOAD_SUCCESS=true || echo "Google CDN failed"
        fi
        
        # 尝试源4: 系统包管理器
        if ! $DOWNLOAD_SUCCESS; then
          echo "Trying system package manager..."
          sudo apt-get install -y chromium-chromedriver && DOWNLOAD_SUCCESS=true || echo "System package manager failed"
        fi
        
        if ! $DOWNLOAD_SUCCESS; then
          echo "All download sources failed"
          exit 1
        fi
        
        # 如果是通过wget下载的，需要解压
        if [ -f /tmp/chromedriver.zip ]; then
          echo "Extracting ChromeDriver..."
          unzip -q /tmp/chromedriver.zip -d /tmp/
          
          # 查找chromedriver可执行文件
          CHROMEDRIVER_PATH=""
          for path in /tmp/chromedriver-linux64/chromedriver /tmp/chromedriver/chromedriver /tmp/chromedriver; do
            if [ -f "$path" ]; then
              CHROMEDRIVER_PATH="$path"
              break
            fi
          done
          
          if [ -z "$CHROMEDRIVER_PATH" ]; then
            echo "ChromeDriver executable not found in extracted files"
            ls -la /tmp/
            exit 1
          fi
          
          echo "Found ChromeDriver at: $CHROMEDRIVER_PATH"
          sudo cp "$CHROMEDRIVER_PATH" /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
        fi
    
    - name: Verify ChromeDriver installation
      run: |
        echo "Verifying ChromeDriver installation..."
        
        # 检查文件是否存在
        if [ ! -f /usr/local/bin/chromedriver ]; then
          echo "ChromeDriver not found at /usr/local/bin/chromedriver"
          exit 1
        fi
        
        # 检查是否可执行
        if [ ! -x /usr/local/bin/chromedriver ]; then
          echo "ChromeDriver is not executable"
          exit 1
        fi
        
        # 检查是否在PATH中
        if ! command -v chromedriver > /dev/null; then
          echo "ChromeDriver not found in PATH"
          exit 1
        fi
        
        # 检查版本
        CHROMEDRIVER_VERSION=$(chromedriver --version)
        echo "ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        echo "ChromeDriver installation verified successfully"
    
    - name: Test ChromeDriver with Python
      run: |
        echo "Testing ChromeDriver with Python..."
        python test_chromedriver_install.py
    
    - name: Test simple ChromeDriver
      run: |
        echo "Testing simple ChromeDriver functionality..."
        python test_simple.py

  mining:
    runs-on: ubuntu-latest
    needs: test-chromedriver
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Chrome and ChromeDriver
      run: |
        # 安装Chrome
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # 获取Chrome版本
        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | awk -F'.' '{print $1}')
        echo "Chrome version: $CHROME_VERSION"
        
        # 下载ChromeDriver
        if [ "$CHROME_VERSION" -ge 115 ]; then
          CHROMEDRIVER_VERSION="120.0.6099.109"
        else
          CHROMEDRIVER_VERSION="$CHROME_VERSION.0.6045.105"
        fi
        
        echo "Using ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # 尝试下载ChromeDriver
        wget -q --timeout=30 --tries=3 -O /tmp/chromedriver.zip "https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" || \
        wget -q --timeout=30 --tries=3 -O /tmp/chromedriver.zip "https://github.com/GoogleChromeLabs/chrome-for-testing/releases/download/$CHROMEDRIVER_VERSION/chromedriver-linux64.zip" || \
        sudo apt-get install -y chromium-chromedriver
        
        if [ -f /tmp/chromedriver.zip ]; then
          unzip -q /tmp/chromedriver.zip -d /tmp/
          sudo cp /tmp/chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
        fi
    
    - name: Test collector retry mechanism
      run: |
        echo "Testing collector retry mechanism..."
        python test_collector_retry.py
    
    - name: Run mining with error handling
      run: |
        echo "Running SSPanel mining with improved error handling..."
        
        # 设置环境变量以启用重试机制
        export MAX_RETRIES=3
        export RETRY_DELAY=30
        
        # 运行采集器，如果遇到CollectorSwitchError则重试
        python src/main.py mining --env=production --collector --classifier --source=local || {
          echo "Mining failed, but this might be due to Google blocking (expected behavior)"
          echo "Checking if any data was collected..."
          
          # 检查是否生成了任何数据文件
          if ls src/database/sspanel_hosts/dataset_*.txt 1> /dev/null 2>&1; then
            echo "Data files found, mining partially successful"
            ls -la src/database/sspanel_hosts/dataset_*.txt
            exit 0
          else
            echo "No data files found, mining completely failed"
            exit 1
          fi
        }
    
    - name: Check results
      run: |
        echo "Checking mining results..."
        
        # 检查是否生成了数据文件
        if ls src/database/sspanel_hosts/dataset_*.txt 1> /dev/null 2>&1; then
          echo "✅ Mining data files found:"
          ls -la src/database/sspanel_hosts/dataset_*.txt
          
          # 显示最新的数据文件内容
          LATEST_FILE=$(ls -t src/database/sspanel_hosts/dataset_*.txt | head -1)
          echo "Latest data file: $LATEST_FILE"
          if [ -f "$LATEST_FILE" ]; then
            echo "First 10 lines:"
            head -10 "$LATEST_FILE"
          fi
        else
          echo "❌ No mining data files found"
        fi
        
        # 检查是否生成了分类文件
        if ls src/database/sspanel_hosts/classifier/mining_*.csv 1> /dev/null 2>&1; then
          echo "✅ Classifier files found:"
          ls -la src/database/sspanel_hosts/classifier/mining_*.csv
        else
          echo "❌ No classifier files found"
        fi 
