name: SSPanel Mining

on:
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点运行
  workflow_dispatch:  # 允许手动触发

jobs:
  mining:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # 安装Chrome浏览器
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # 显示Chrome版本
        echo "Chrome version:"
        google-chrome --version
        
        # 安装ChromeDriver
        echo "Installing ChromeDriver..."
        
        # 使用已知稳定的ChromeDriver版本
        CHROMEDRIVER_VERSION="114.0.5735.90"
        
        # 尝试多个下载源
        echo "Downloading ChromeDriver version: $CHROMEDRIVER_VERSION"
        
        # 尝试从Google官方下载
        if wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip; then
          echo "Downloaded from Google storage"
        elif wget -q "https://github.com/GoogleChromeLabs/chrome-for-testing/releases/download/$CHROMEDRIVER_VERSION/chromedriver-linux64.zip" -O chromedriver.zip; then
          echo "Downloaded from GitHub releases"
        elif wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" -O chromedriver.zip; then
          echo "Downloaded from Google CDN"
        else
          echo "All download sources failed, trying alternative version"
          # 尝试备用版本
          CHROMEDRIVER_VERSION="113.0.5672.63"
          wget -q "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" -O chromedriver.zip || \
          wget -q "https://github.com/GoogleChromeLabs/chrome-for-testing/releases/download/$CHROMEDRIVER_VERSION/chromedriver-linux64.zip" -O chromedriver.zip || \
          wget -q "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROMEDRIVER_VERSION/linux64/chromedriver-linux64.zip" -O chromedriver.zip
        fi
        
        # 解压并安装
        unzip -q chromedriver.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver
        
        # 验证安装
        echo "ChromeDriver version:"
        chromedriver --version
        
        # 设置环境变量
        echo "CHROME_DRIVER_PATH=/usr/local/bin/chromedriver" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run mining
      run: |
        cd src
        python main.py mining --env=production --collector --classifier --source=local
      env:
        CHROME_DRIVER_PATH: /usr/local/bin/chromedriver 
